name: one_roof_server
description: An empty Aqueduct application.
version: 0.0.1
author: Deepak Kumar Jha <dj12885@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  aqueduct: ^4.0.0-b1
  
dev_dependencies:
  test: ^1.15.1
  aqueduct_test: ^2.0.0-b1

# dependency_overrides:
#   postgres: 2.1.1